(function(global){
  "use strict";

  const DOMAIN_VERSION="4.2.0-alpha.2";
  const EXERCISE_SCHEMA_VERSION=1;

  const MOVEMENT_PATTERNS=Object.freeze([
    "squat", "knee_dominant", "hip_hinge", "horizontal_push", "vertical_push", "horizontal_pull",
    "vertical_pull", "hip_extension", "knee_flexion", "knee_extension", "calf_raise",
    "elbow_flexion", "elbow_extension", "shoulder_abduction", "shoulder_flexion",
    "shoulder_external_rotation", "hip_abduction", "hip_adduction", "anti_extension_core",
    "anti_rotation_core", "lateral_core", "trunk_flexion", "hip_flexion_core", "loaded_carry",
    "unilateral_lower_body", "locomotion", "spinal_mobility", "thoracic_rotation",
    "hip_flexor_mobility"
  ]);
  const EXERCISE_CATEGORIES=Object.freeze([
    "strength","cardio","mobility","breathing","pelvic_floor","warm_up","recovery"
  ]);
  const EQUIPMENT_TAXONOMY=Object.freeze([
    "bodyweight", "mat", "bench", "adjustable_bench", "decline_bench", "preacher_bench",
    "dumbbells", "barbell", "ez_bar", "trap_bar", "plates", "squat_rack", "smith_machine",
    "cable_machine", "resistance_band", "pull_up_bar", "dip_station", "ab_wheel", "step",
    "chest_press_machine", "shoulder_press_machine", "lateral_raise_machine", "leg_press",
    "leg_extension", "seated_leg_curl", "lying_leg_curl", "hip_thrust_machine",
    "hip_abduction_machine", "hip_adduction_machine", "lat_pulldown", "seated_row", "row_machine",
    "t_bar_row_machine", "pec_deck", "hack_squat_machine", "calf_raise_machine",
    "seated_calf_raise_machine", "assisted_pullup_dip_machine", "nordic_bench", "treadmill",
    "stationary_bike", "elliptical", "stability_ball"
  ]);
  const EXPERIENCE_LEVELS=Object.freeze(["beginner","intermediate","advanced","returning"]);
  const RECORD_TYPES=Object.freeze([
    "weight_reps","bodyweight_reps","assisted_reps","duration","distance_time",
    "guided_repetitions","mobility_quality"
  ]);
  const EQUIPMENT_PRESETS=Object.freeze({
    full:Object.freeze([...EQUIPMENT_TAXONOMY]),
    gym_full:Object.freeze([...EQUIPMENT_TAXONOMY]),
    home_dumbbells:Object.freeze(["bodyweight","mat","dumbbells","bench"]),
    home_basic:Object.freeze(["bodyweight","mat","resistance_band"]),
    bodyweight:Object.freeze(["bodyweight","mat"])
  });
  const PROGRAMMING_PRIORITY=Object.freeze([
    "life_state","restrictions","primary_goal","training_phase","secondary_goals","preferences"
  ]);
  const PROGRAMMING_RULES=Object.freeze({
    return_to_training:Object.freeze({
      mainSets:[2,3],accessorySets:[1,2],mainRepRange:[8,12],accessoryRepRange:[10,15],
      targetRir:[3,4],mainRestSeconds:[90,150],accessoryRestSeconds:[60,90],
      maxTechnicalComplexity:2,preferSupported:true
    }),
    muscle_gain:Object.freeze({
      mainSets:[3,4],accessorySets:[2,4],mainRepRange:[6,12],accessoryRepRange:[10,20],
      targetRir:[1,3],mainRestSeconds:[120,180],accessoryRestSeconds:[60,120],
      maxTechnicalComplexity:4,preferSupported:false
    }),
    strength_gain:Object.freeze({
      mainSets:[3,5],accessorySets:[2,3],mainRepRange:[3,6],accessoryRepRange:[6,12],
      targetRir:[2,3],mainRestSeconds:[180,300],accessoryRestSeconds:[90,150],
      maxTechnicalComplexity:4,preferSupported:false
    }),
    fat_loss:Object.freeze({
      mainSets:[2,4],accessorySets:[2,3],mainRepRange:[6,12],accessoryRepRange:[10,15],
      targetRir:[2,4],mainRestSeconds:[90,180],accessoryRestSeconds:[60,120],
      maxTechnicalComplexity:3,preferSupported:false
    }),
    general_health:Object.freeze({
      mainSets:[2,3],accessorySets:[1,3],mainRepRange:[8,12],accessoryRepRange:[10,15],
      targetRir:[2,4],mainRestSeconds:[90,150],accessoryRestSeconds:[60,90],
      maxTechnicalComplexity:3,preferSupported:false
    }),
    maintenance:Object.freeze({
      mainSets:[2,3],accessorySets:[1,2],mainRepRange:[6,12],accessoryRepRange:[10,15],
      targetRir:[2,4],mainRestSeconds:[90,180],accessoryRestSeconds:[60,90],
      maxTechnicalComplexity:4,preferSupported:false
    })
  });

  const EQUIPMENT_ALIASES=Object.freeze({
    "peso corporal":"bodyweight",
    "bodyweight":"bodyweight",
    "esterilla":"mat",
    "colchoneta":"mat",
    "mat":"mat",
    "banco":"bench",
    "bench":"bench",
    "banco ajustable":"adjustable_bench",
    "banco declinado":"decline_bench",
    "banco predicador":"preacher_bench",
    "mancuerna":"dumbbells",
    "mancuernas":"dumbbells",
    "dumbbells":"dumbbells",
    "barra":"barbell",
    "barbell":"barbell",
    "barra ez":"ez_bar",
    "barra z":"ez_bar",
    "barra hexagonal":"trap_bar",
    "trap bar":"trap_bar",
    "discos":"plates",
    "plates":"plates",
    "rack":"squat_rack",
    "jaula":"squat_rack",
    "polea":"cable_machine",
    "poleas":"cable_machine",
    "banda":"resistance_band",
    "bandas":"resistance_band",
    "banda elastica":"resistance_band",
    "barra dominadas":"pull_up_bar",
    "estacion fondos":"dip_station",
    "rueda abdominal":"ab_wheel",
    "step":"step",
    "maquina":"machine",
    "máquina":"machine",
    "cinta":"treadmill",
    "bicicleta estatica":"stationary_bike",
    "eliptica":"elliptical",
    "gimnasio completo":"gym_full",
    "full":"full",
    "casa con mancuernas":"home_dumbbells",
    "home dumbbells":"home_dumbbells",
    "casa basica":"home_basic",
    "home basic":"home_basic"
  });

  const LEGACY_EXERCISE_METADATA=Object.freeze({
    "bench-press":{
      "aliases":[
        "Press banca",
        "Press con barra"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"barbell_flat_press",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "triceps",
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "barbell",
        "plates",
        "bench",
        "squat_rack"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "supine"
      ],
      "loadingTypes":[
        "free_weight"
      ],
      "prolongedSupine":true
    },
    "dumbbell-bench-press":{
      "aliases":[
        "Press plano con mancuernas",
        "Press mancuernas plano"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"dumbbell_flat_press",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "triceps",
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "dumbbells",
        "bench"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "supine"
      ],
      "loadingTypes":[
        "free_weight"
      ],
      "prolongedSupine":true
    },
    "incline-barbell-press":{
      "aliases":[
        "Press inclinado barra"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"barbell_incline_press",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "triceps",
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "barbell",
        "plates",
        "adjustable_bench",
        "squat_rack"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "incline_supine"
      ],
      "loadingTypes":[
        "free_weight"
      ],
      "prolongedSupine":true
    },
    "incline-db-press":{
      "aliases":[
        "Press inclinado mancuernas"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"dumbbell_incline_press",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "triceps",
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "dumbbells",
        "adjustable_bench"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "incline_supine"
      ],
      "loadingTypes":[
        "free_weight"
      ],
      "prolongedSupine":true
    },
    "decline-bench-press":{
      "aliases":[
        "Press declinado"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"barbell_decline_press",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "triceps",
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "barbell",
        "plates",
        "decline_bench"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "decline_supine"
      ],
      "loadingTypes":[
        "free_weight"
      ],
      "prolongedSupine":true
    },
    "machine-chest-press":{
      "aliases":[
        "Press pecho máquina",
        "Press en máquina"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"machine_chest_press",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "triceps",
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "chest_press_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "cable-chest-fly":{
      "aliases":[
        "Cruce de poleas",
        "Aperturas con cable"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"cable_chest_fly",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "pec-deck-fly":{
      "aliases":[
        "Peck deck",
        "Contractora de pecho",
        "Aperturas máquina"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"machine_chest_fly",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "pec_deck"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "dumbbell-fly":{
      "aliases":[
        "Aperturas mancuernas"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"dumbbell_chest_fly",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "dumbbells",
        "bench"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "supine"
      ],
      "loadingTypes":[
        "free_weight"
      ],
      "prolongedSupine":true
    },
    "push-up":{
      "aliases":[
        "Flexión de brazos",
        "Lagartijas"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"bodyweight_push_up",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "triceps",
        "anterior_deltoid",
        "trunk"
      ],
      "requiredEquipment":[
        "bodyweight"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "prone"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "chest-dip":{
      "aliases":[
        "Fondos de pecho",
        "Fondos inclinados"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"bodyweight_chest_dip",
      "primaryMuscles":[
        "chest"
      ],
      "secondaryMuscles":[
        "triceps",
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "dip_station"
      ],
      "difficulty":"advanced",
      "technicalComplexity":3,
      "stabilityDemand":3,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "supported_hanging"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "lat-pulldown":{
      "aliases":[
        "Jalón",
        "Jalón polea"
      ],
      "movementPattern":"vertical_pull",
      "movementSubpattern":"wide_grip_lat_pulldown",
      "primaryMuscles":[
        "latissimus_dorsi"
      ],
      "secondaryMuscles":[
        "biceps",
        "upper_back"
      ],
      "requiredEquipment":[
        "lat_pulldown"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "neutral-grip-lat-pulldown":{
      "aliases":[
        "Jalón neutro",
        "Jalón agarre neutro"
      ],
      "movementPattern":"vertical_pull",
      "movementSubpattern":"neutral_grip_lat_pulldown",
      "primaryMuscles":[
        "latissimus_dorsi"
      ],
      "secondaryMuscles":[
        "biceps",
        "upper_back"
      ],
      "requiredEquipment":[
        "lat_pulldown"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "pull-up":{
      "aliases":[
        "Dominadas",
        "Dominada prona"
      ],
      "movementPattern":"vertical_pull",
      "movementSubpattern":"pronated_pull_up",
      "primaryMuscles":[
        "latissimus_dorsi",
        "upper_back"
      ],
      "secondaryMuscles":[
        "biceps",
        "forearms"
      ],
      "requiredEquipment":[
        "pull_up_bar"
      ],
      "difficulty":"advanced",
      "technicalComplexity":3,
      "stabilityDemand":3,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "hanging"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "assisted-pull-up":{
      "aliases":[
        "Dominada asistida",
        "Dominadas en máquina asistida"
      ],
      "movementPattern":"vertical_pull",
      "movementSubpattern":"assisted_pull_up",
      "primaryMuscles":[
        "latissimus_dorsi",
        "upper_back"
      ],
      "secondaryMuscles":[
        "biceps"
      ],
      "requiredEquipment":[
        "assisted_pullup_dip_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "supported_hanging"
      ],
      "loadingTypes":[
        "assisted"
      ]
    },
    "chin-up":{
      "aliases":[
        "Dominada supina",
        "Chin ups"
      ],
      "movementPattern":"vertical_pull",
      "movementSubpattern":"supinated_chin_up",
      "primaryMuscles":[
        "latissimus_dorsi"
      ],
      "secondaryMuscles":[
        "biceps",
        "upper_back"
      ],
      "requiredEquipment":[
        "pull_up_bar"
      ],
      "difficulty":"advanced",
      "technicalComplexity":3,
      "stabilityDemand":3,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "hanging"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "barbell-row":{
      "aliases":[
        "Remo barra"
      ],
      "movementPattern":"horizontal_pull",
      "movementSubpattern":"barbell_bent_over_row",
      "primaryMuscles":[
        "upper_back",
        "latissimus_dorsi"
      ],
      "secondaryMuscles":[
        "biceps",
        "posterior_deltoid"
      ],
      "requiredEquipment":[
        "barbell",
        "plates"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":3,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "bent_over"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "seated-cable-row":{
      "aliases":[
        "Remo en polea baja",
        "Remo polea sentado"
      ],
      "movementPattern":"horizontal_pull",
      "movementSubpattern":"seated_cable_row",
      "primaryMuscles":[
        "upper_back",
        "latissimus_dorsi"
      ],
      "secondaryMuscles":[
        "biceps",
        "posterior_deltoid"
      ],
      "requiredEquipment":[
        "seated_row"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "machine-row":{
      "aliases":[
        "Remo máquina",
        "Remo guiado"
      ],
      "movementPattern":"horizontal_pull",
      "movementSubpattern":"machine_supported_row",
      "primaryMuscles":[
        "upper_back",
        "latissimus_dorsi"
      ],
      "secondaryMuscles":[
        "biceps",
        "posterior_deltoid"
      ],
      "requiredEquipment":[
        "row_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "one-arm-dumbbell-row":{
      "aliases":[
        "Remo unilateral con mancuerna",
        "Remo mancuerna"
      ],
      "movementPattern":"horizontal_pull",
      "movementSubpattern":"single_arm_dumbbell_row",
      "primaryMuscles":[
        "latissimus_dorsi",
        "upper_back"
      ],
      "secondaryMuscles":[
        "biceps",
        "posterior_deltoid"
      ],
      "requiredEquipment":[
        "dumbbells",
        "bench"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "supported_bent_over"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "chest-supported-db-row":{
      "aliases":[
        "Remo pecho apoyado",
        "Remo inclinado con apoyo"
      ],
      "movementPattern":"horizontal_pull",
      "movementSubpattern":"chest_supported_dumbbell_row",
      "primaryMuscles":[
        "upper_back",
        "latissimus_dorsi"
      ],
      "secondaryMuscles":[
        "biceps",
        "posterior_deltoid"
      ],
      "requiredEquipment":[
        "dumbbells",
        "adjustable_bench"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "incline_prone"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "t-bar-row":{
      "aliases":[
        "Remo T",
        "T bar row"
      ],
      "movementPattern":"horizontal_pull",
      "movementSubpattern":"t_bar_row",
      "primaryMuscles":[
        "upper_back",
        "latissimus_dorsi"
      ],
      "secondaryMuscles":[
        "biceps",
        "posterior_deltoid"
      ],
      "requiredEquipment":[
        "t_bar_row_machine"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "bent_over"
      ],
      "loadingTypes":[
        "plate_loaded"
      ]
    },
    "straight-arm-pulldown":{
      "aliases":[
        "Jalón brazos rectos",
        "Pullover polea"
      ],
      "movementPattern":"vertical_pull",
      "movementSubpattern":"straight_arm_cable_pulldown",
      "primaryMuscles":[
        "latissimus_dorsi"
      ],
      "secondaryMuscles":[
        "triceps",
        "trunk"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "face-pull":{
      "aliases":[
        "Tirón a la cara",
        "Facepull"
      ],
      "movementPattern":"shoulder_external_rotation",
      "movementSubpattern":"cable_face_pull",
      "primaryMuscles":[
        "posterior_deltoid",
        "rotator_cuff"
      ],
      "secondaryMuscles":[
        "upper_back",
        "lower_traps"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "back-squat":{
      "aliases":[
        "Sentadilla con barra"
      ],
      "movementPattern":"squat",
      "movementSubpattern":"barbell_back_squat",
      "primaryMuscles":[
        "quadriceps",
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings",
        "trunk"
      ],
      "requiredEquipment":[
        "barbell",
        "plates",
        "squat_rack"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":4,
      "stabilityDemand":4,
      "balanceDemand":3,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "front-squat":{
      "aliases":[
        "Sentadilla frontal con barra"
      ],
      "movementPattern":"squat",
      "movementSubpattern":"barbell_front_squat",
      "primaryMuscles":[
        "quadriceps",
        "glutes"
      ],
      "secondaryMuscles":[
        "trunk",
        "upper_back"
      ],
      "requiredEquipment":[
        "barbell",
        "plates",
        "squat_rack"
      ],
      "difficulty":"advanced",
      "technicalComplexity":4,
      "stabilityDemand":4,
      "balanceDemand":3,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "goblet-squat":{
      "aliases":[
        "Sentadilla copa",
        "Goblet squat"
      ],
      "movementPattern":"squat",
      "movementSubpattern":"goblet_squat",
      "primaryMuscles":[
        "quadriceps",
        "glutes"
      ],
      "secondaryMuscles":[
        "trunk"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "smith-squat":{
      "aliases":[
        "Sentadilla Smith",
        "Sentadilla multipower"
      ],
      "movementPattern":"squat",
      "movementSubpattern":"smith_machine_squat",
      "primaryMuscles":[
        "quadriceps",
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings"
      ],
      "requiredEquipment":[
        "smith_machine",
        "plates"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "guided_bar"
      ]
    },
    "hack-squat":{
      "aliases":[
        "Hack squat",
        "Jaca"
      ],
      "movementPattern":"knee_dominant",
      "movementSubpattern":"machine_hack_squat",
      "primaryMuscles":[
        "quadriceps",
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings"
      ],
      "requiredEquipment":[
        "hack_squat_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "supported_standing"
      ],
      "loadingTypes":[
        "plate_loaded"
      ]
    },
    "leg-press":{
      "aliases":[
        "Prensa"
      ],
      "movementPattern":"knee_dominant",
      "movementSubpattern":"machine_leg_press",
      "primaryMuscles":[
        "quadriceps",
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings"
      ],
      "requiredEquipment":[
        "leg_press"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "bulgarian-split-squat":{
      "aliases":[
        "Búlgara",
        "Split squat búlgaro"
      ],
      "movementPattern":"unilateral_lower_body",
      "movementSubpattern":"rear_foot_elevated_split_squat",
      "primaryMuscles":[
        "quadriceps",
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings",
        "trunk"
      ],
      "requiredEquipment":[
        "dumbbells",
        "bench"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":4,
      "balanceDemand":4,
      "supported":false,
      "closedChain":true,
      "unilateral":true,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "reverse-lunge":{
      "aliases":[
        "Zancada inversa",
        "Lunge atrás"
      ],
      "movementPattern":"unilateral_lower_body",
      "movementSubpattern":"reverse_lunge",
      "primaryMuscles":[
        "quadriceps",
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings",
        "trunk"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":3,
      "balanceDemand":3,
      "supported":false,
      "closedChain":true,
      "unilateral":true,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "walking-lunge":{
      "aliases":[
        "Zancadas andando",
        "Walking lunges"
      ],
      "movementPattern":"unilateral_lower_body",
      "movementSubpattern":"walking_lunge",
      "primaryMuscles":[
        "quadriceps",
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings",
        "calves",
        "trunk"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":2,
      "stabilityDemand":4,
      "balanceDemand":4,
      "supported":false,
      "closedChain":true,
      "unilateral":true,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "step-up":{
      "aliases":[
        "Step up",
        "Subida a banco"
      ],
      "movementPattern":"unilateral_lower_body",
      "movementSubpattern":"weighted_step_up",
      "primaryMuscles":[
        "quadriceps",
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings",
        "calves"
      ],
      "requiredEquipment":[
        "dumbbells",
        "step"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":3,
      "balanceDemand":3,
      "supported":false,
      "closedChain":true,
      "unilateral":true,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "leg-extension":{
      "aliases":[
        "Extensión de cuádriceps",
        "Cuádriceps máquina"
      ],
      "movementPattern":"knee_extension",
      "movementSubpattern":"machine_knee_extension",
      "primaryMuscles":[
        "quadriceps"
      ],
      "secondaryMuscles":[],
      "requiredEquipment":[
        "leg_extension"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "hip-thrust":{
      "aliases":[
        "Empuje de cadera con barra",
        "Hip thrust"
      ],
      "movementPattern":"hip_extension",
      "movementSubpattern":"barbell_hip_thrust",
      "primaryMuscles":[
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings",
        "trunk"
      ],
      "requiredEquipment":[
        "barbell",
        "plates",
        "bench"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "upper_back_supported"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "machine-hip-thrust":{
      "aliases":[
        "Empuje de cadera en máquina"
      ],
      "movementPattern":"hip_extension",
      "movementSubpattern":"machine_hip_thrust",
      "primaryMuscles":[
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings"
      ],
      "requiredEquipment":[
        "hip_thrust_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "upper_back_supported"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "glute-bridge":{
      "aliases":[
        "Puente de cadera",
        "Glute bridge"
      ],
      "movementPattern":"hip_extension",
      "movementSubpattern":"bodyweight_glute_bridge",
      "primaryMuscles":[
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings",
        "trunk"
      ],
      "requiredEquipment":[
        "bodyweight",
        "mat"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "supine"
      ],
      "loadingTypes":[
        "bodyweight"
      ],
      "prolongedSupine":true
    },
    "cable-kickback":{
      "aliases":[
        "Patada de glúteo en polea",
        "Kickback en polea"
      ],
      "movementPattern":"hip_extension",
      "movementSubpattern":"standing_cable_hip_extension",
      "primaryMuscles":[
        "glutes"
      ],
      "secondaryMuscles":[
        "hamstrings"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":3,
      "balanceDemand":3,
      "supported":false,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "romanian-deadlift":{
      "aliases":[
        "Peso muerto rumano con barra"
      ],
      "movementPattern":"hip_hinge",
      "movementSubpattern":"barbell_romanian_deadlift",
      "primaryMuscles":[
        "hamstrings",
        "glutes"
      ],
      "secondaryMuscles":[
        "spinal_erectors",
        "forearms"
      ],
      "requiredEquipment":[
        "barbell",
        "plates"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":3,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "db-romanian-deadlift":{
      "aliases":[
        "Rumano con mancuernas",
        "RDL mancuernas"
      ],
      "movementPattern":"hip_hinge",
      "movementSubpattern":"dumbbell_romanian_deadlift",
      "primaryMuscles":[
        "hamstrings",
        "glutes"
      ],
      "secondaryMuscles":[
        "spinal_erectors",
        "forearms"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "conventional-deadlift":{
      "aliases":[
        "Peso muerto",
        "Deadlift convencional"
      ],
      "movementPattern":"hip_hinge",
      "movementSubpattern":"barbell_conventional_deadlift",
      "primaryMuscles":[
        "glutes",
        "hamstrings",
        "spinal_erectors"
      ],
      "secondaryMuscles":[
        "quadriceps",
        "upper_back",
        "forearms"
      ],
      "requiredEquipment":[
        "barbell",
        "plates"
      ],
      "difficulty":"advanced",
      "technicalComplexity":5,
      "stabilityDemand":4,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "trap-bar-deadlift":{
      "aliases":[
        "Peso muerto trap bar",
        "Peso muerto barra hexagonal"
      ],
      "movementPattern":"hip_hinge",
      "movementSubpattern":"trap_bar_deadlift",
      "primaryMuscles":[
        "glutes",
        "quadriceps",
        "hamstrings"
      ],
      "secondaryMuscles":[
        "spinal_erectors",
        "forearms"
      ],
      "requiredEquipment":[
        "trap_bar",
        "plates"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":3,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "sumo-deadlift":{
      "aliases":[
        "Peso muerto estilo sumo"
      ],
      "movementPattern":"hip_hinge",
      "movementSubpattern":"barbell_sumo_deadlift",
      "primaryMuscles":[
        "glutes",
        "adductors",
        "hamstrings"
      ],
      "secondaryMuscles":[
        "quadriceps",
        "spinal_erectors"
      ],
      "requiredEquipment":[
        "barbell",
        "plates"
      ],
      "difficulty":"advanced",
      "technicalComplexity":4,
      "stabilityDemand":4,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "leg-curl":{
      "aliases":[
        "Curl femoral",
        "Curl femoral máquina"
      ],
      "movementPattern":"knee_flexion",
      "movementSubpattern":"seated_leg_curl",
      "primaryMuscles":[
        "hamstrings"
      ],
      "secondaryMuscles":[
        "calves"
      ],
      "requiredEquipment":[
        "seated_leg_curl"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "lying-leg-curl":{
      "aliases":[
        "Curl femoral acostado"
      ],
      "movementPattern":"knee_flexion",
      "movementSubpattern":"lying_leg_curl",
      "primaryMuscles":[
        "hamstrings"
      ],
      "secondaryMuscles":[
        "calves"
      ],
      "requiredEquipment":[
        "lying_leg_curl"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "prone"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "single-leg-curl":{
      "aliases":[
        "Curl femoral a una pierna"
      ],
      "movementPattern":"knee_flexion",
      "movementSubpattern":"single_leg_machine_curl",
      "primaryMuscles":[
        "hamstrings"
      ],
      "secondaryMuscles":[
        "calves"
      ],
      "requiredEquipment":[
        "seated_leg_curl"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "cable-pull-through":{
      "aliases":[
        "Pull through",
        "Jalón de cadera en polea"
      ],
      "movementPattern":"hip_hinge",
      "movementSubpattern":"cable_pull_through",
      "primaryMuscles":[
        "glutes",
        "hamstrings"
      ],
      "secondaryMuscles":[
        "trunk"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":2,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "machine-hip-abduction":{
      "aliases":[
        "Abductores en máquina",
        "Máquina de abductores"
      ],
      "movementPattern":"hip_abduction",
      "movementSubpattern":"machine_hip_abduction",
      "primaryMuscles":[
        "gluteus_medius",
        "gluteus_minimus"
      ],
      "secondaryMuscles":[
        "glutes"
      ],
      "requiredEquipment":[
        "hip_abduction_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "cable-hip-abduction":{
      "aliases":[
        "Abducción en polea",
        "Patada lateral en polea"
      ],
      "movementPattern":"hip_abduction",
      "movementSubpattern":"standing_cable_hip_abduction",
      "primaryMuscles":[
        "gluteus_medius",
        "gluteus_minimus"
      ],
      "secondaryMuscles":[
        "glutes"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":2,
      "stabilityDemand":3,
      "balanceDemand":3,
      "supported":false,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "machine-hip-adduction":{
      "aliases":[
        "Aductores en máquina",
        "Máquina de aductores"
      ],
      "movementPattern":"hip_adduction",
      "movementSubpattern":"machine_hip_adduction",
      "primaryMuscles":[
        "adductors"
      ],
      "secondaryMuscles":[
        "gracilis"
      ],
      "requiredEquipment":[
        "hip_adduction_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "nordic-hamstring-curl":{
      "aliases":[
        "Curl nórdico",
        "Nordic curl"
      ],
      "movementPattern":"knee_flexion",
      "movementSubpattern":"nordic_hamstring_curl",
      "primaryMuscles":[
        "hamstrings"
      ],
      "secondaryMuscles":[
        "glutes",
        "calves"
      ],
      "requiredEquipment":[
        "nordic_bench"
      ],
      "difficulty":"advanced",
      "technicalComplexity":3,
      "stabilityDemand":3,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "kneeling"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "overhead-press":{
      "aliases":[
        "Press militar con barra"
      ],
      "movementPattern":"vertical_push",
      "movementSubpattern":"standing_barbell_overhead_press",
      "primaryMuscles":[
        "deltoids"
      ],
      "secondaryMuscles":[
        "triceps",
        "upper_chest"
      ],
      "requiredEquipment":[
        "barbell",
        "plates"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":3,
      "balanceDemand":2,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "db-shoulder-press":{
      "aliases":[
        "Press hombro mancuernas",
        "Press sentado con mancuernas"
      ],
      "movementPattern":"vertical_push",
      "movementSubpattern":"seated_dumbbell_shoulder_press",
      "primaryMuscles":[
        "deltoids"
      ],
      "secondaryMuscles":[
        "triceps",
        "upper_chest"
      ],
      "requiredEquipment":[
        "dumbbells",
        "adjustable_bench"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "machine-shoulder-press":{
      "aliases":[
        "Press hombro máquina"
      ],
      "movementPattern":"vertical_push",
      "movementSubpattern":"machine_shoulder_press",
      "primaryMuscles":[
        "deltoids"
      ],
      "secondaryMuscles":[
        "triceps"
      ],
      "requiredEquipment":[
        "shoulder_press_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "arnold-press":{
      "aliases":[
        "Press Arnold con mancuernas"
      ],
      "movementPattern":"vertical_push",
      "movementSubpattern":"dumbbell_arnold_press",
      "primaryMuscles":[
        "deltoids"
      ],
      "secondaryMuscles":[
        "triceps",
        "upper_chest"
      ],
      "requiredEquipment":[
        "dumbbells",
        "adjustable_bench"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "lateral-raise":{
      "aliases":[
        "Elevación lateral"
      ],
      "movementPattern":"shoulder_abduction",
      "movementSubpattern":"dumbbell_lateral_raise",
      "primaryMuscles":[
        "lateral_deltoid"
      ],
      "secondaryMuscles":[
        "upper_traps"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "cable-lateral-raise":{
      "aliases":[
        "Elevaciones laterales en polea"
      ],
      "movementPattern":"shoulder_abduction",
      "movementSubpattern":"single_arm_cable_lateral_raise",
      "primaryMuscles":[
        "lateral_deltoid"
      ],
      "secondaryMuscles":[
        "upper_traps"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "machine-lateral-raise":{
      "aliases":[
        "Laterales en máquina",
        "Máquina de deltoide lateral"
      ],
      "movementPattern":"shoulder_abduction",
      "movementSubpattern":"machine_lateral_raise",
      "primaryMuscles":[
        "lateral_deltoid"
      ],
      "secondaryMuscles":[
        "upper_traps"
      ],
      "requiredEquipment":[
        "lateral_raise_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "front-raise":{
      "aliases":[
        "Elevaciones frontales"
      ],
      "movementPattern":"shoulder_flexion",
      "movementSubpattern":"dumbbell_front_raise",
      "primaryMuscles":[
        "anterior_deltoid"
      ],
      "secondaryMuscles":[
        "upper_chest"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "rear-delt-fly":{
      "aliases":[
        "Aperturas posteriores",
        "Elevación posterior"
      ],
      "movementPattern":"horizontal_pull",
      "movementSubpattern":"dumbbell_rear_delt_fly",
      "primaryMuscles":[
        "posterior_deltoid"
      ],
      "secondaryMuscles":[
        "upper_back"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "bent_over"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "reverse-pec-deck":{
      "aliases":[
        "Peck deck inverso",
        "Reverse fly máquina"
      ],
      "movementPattern":"horizontal_pull",
      "movementSubpattern":"machine_reverse_fly",
      "primaryMuscles":[
        "posterior_deltoid"
      ],
      "secondaryMuscles":[
        "upper_back",
        "rotator_cuff"
      ],
      "requiredEquipment":[
        "pec_deck"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "upright-row":{
      "aliases":[
        "Remo vertical",
        "Upright row"
      ],
      "movementPattern":"shoulder_abduction",
      "movementSubpattern":"barbell_upright_row",
      "primaryMuscles":[
        "lateral_deltoid",
        "upper_traps"
      ],
      "secondaryMuscles":[
        "biceps"
      ],
      "requiredEquipment":[
        "barbell",
        "plates"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "cable-external-rotation":{
      "aliases":[
        "Rotación externa en polea"
      ],
      "movementPattern":"shoulder_external_rotation",
      "movementSubpattern":"cable_external_rotation",
      "primaryMuscles":[
        "rotator_cuff"
      ],
      "secondaryMuscles":[
        "posterior_deltoid"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "biceps-curl":{
      "aliases":[
        "Curl de bíceps",
        "Curl bíceps"
      ],
      "movementPattern":"elbow_flexion",
      "movementSubpattern":"standing_dumbbell_curl",
      "primaryMuscles":[
        "biceps"
      ],
      "secondaryMuscles":[
        "forearms"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "barbell-curl":{
      "aliases":[
        "Curl con barra",
        "Curl barra recta"
      ],
      "movementPattern":"elbow_flexion",
      "movementSubpattern":"barbell_biceps_curl",
      "primaryMuscles":[
        "biceps"
      ],
      "secondaryMuscles":[
        "forearms"
      ],
      "requiredEquipment":[
        "barbell",
        "plates"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "ez-bar-curl":{
      "aliases":[
        "Curl barra Z",
        "Curl barra EZ"
      ],
      "movementPattern":"elbow_flexion",
      "movementSubpattern":"ez_bar_biceps_curl",
      "primaryMuscles":[
        "biceps"
      ],
      "secondaryMuscles":[
        "forearms"
      ],
      "requiredEquipment":[
        "ez_bar",
        "plates"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "hammer-curl":{
      "aliases":[
        "Curl neutro",
        "Martillo con mancuernas"
      ],
      "movementPattern":"elbow_flexion",
      "movementSubpattern":"dumbbell_hammer_curl",
      "primaryMuscles":[
        "brachialis",
        "biceps"
      ],
      "secondaryMuscles":[
        "forearms"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "incline-db-curl":{
      "aliases":[
        "Curl bíceps banco inclinado"
      ],
      "movementPattern":"elbow_flexion",
      "movementSubpattern":"incline_dumbbell_curl",
      "primaryMuscles":[
        "biceps"
      ],
      "secondaryMuscles":[
        "forearms"
      ],
      "requiredEquipment":[
        "dumbbells",
        "adjustable_bench"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "incline_seated"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "preacher-curl":{
      "aliases":[
        "Curl Scott",
        "Predicador"
      ],
      "movementPattern":"elbow_flexion",
      "movementSubpattern":"preacher_curl",
      "primaryMuscles":[
        "biceps"
      ],
      "secondaryMuscles":[
        "brachialis",
        "forearms"
      ],
      "requiredEquipment":[
        "ez_bar",
        "plates",
        "preacher_bench"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "cable-curl":{
      "aliases":[
        "Curl polea",
        "Curl cable"
      ],
      "movementPattern":"elbow_flexion",
      "movementSubpattern":"cable_biceps_curl",
      "primaryMuscles":[
        "biceps"
      ],
      "secondaryMuscles":[
        "forearms"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "concentration-curl":{
      "aliases":[
        "Curl concentración"
      ],
      "movementPattern":"elbow_flexion",
      "movementSubpattern":"seated_concentration_curl",
      "primaryMuscles":[
        "biceps"
      ],
      "secondaryMuscles":[
        "forearms"
      ],
      "requiredEquipment":[
        "dumbbells",
        "bench"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "triceps-pushdown":{
      "aliases":[
        "Extensión de tríceps en polea",
        "Tríceps polea"
      ],
      "movementPattern":"elbow_extension",
      "movementSubpattern":"straight_bar_pushdown",
      "primaryMuscles":[
        "triceps"
      ],
      "secondaryMuscles":[],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "rope-pushdown":{
      "aliases":[
        "Tríceps cuerda",
        "Pushdown con cuerda"
      ],
      "movementPattern":"elbow_extension",
      "movementSubpattern":"rope_triceps_pushdown",
      "primaryMuscles":[
        "triceps"
      ],
      "secondaryMuscles":[],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "overhead-cable-extension":{
      "aliases":[
        "Tríceps overhead en polea",
        "Extensión francesa en polea"
      ],
      "movementPattern":"elbow_extension",
      "movementSubpattern":"overhead_cable_triceps_extension",
      "primaryMuscles":[
        "triceps"
      ],
      "secondaryMuscles":[
        "trunk"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "skull-crusher":{
      "aliases":[
        "Rompecráneos",
        "Skull crusher",
        "Press francés"
      ],
      "movementPattern":"elbow_extension",
      "movementSubpattern":"lying_ez_bar_triceps_extension",
      "primaryMuscles":[
        "triceps"
      ],
      "secondaryMuscles":[],
      "requiredEquipment":[
        "ez_bar",
        "plates",
        "bench"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "supine"
      ],
      "loadingTypes":[
        "free_weight"
      ],
      "prolongedSupine":true
    },
    "close-grip-bench-press":{
      "aliases":[
        "Press cerrado",
        "Press banca cerrado"
      ],
      "movementPattern":"horizontal_push",
      "movementSubpattern":"close_grip_bench_press",
      "primaryMuscles":[
        "triceps"
      ],
      "secondaryMuscles":[
        "chest",
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "barbell",
        "plates",
        "bench",
        "squat_rack"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "supine"
      ],
      "loadingTypes":[
        "free_weight"
      ],
      "prolongedSupine":true
    },
    "triceps-dip":{
      "aliases":[
        "Fondos de tríceps",
        "Fondos verticales"
      ],
      "movementPattern":"elbow_extension",
      "movementSubpattern":"bodyweight_triceps_dip",
      "primaryMuscles":[
        "triceps"
      ],
      "secondaryMuscles":[
        "chest",
        "anterior_deltoid"
      ],
      "requiredEquipment":[
        "dip_station"
      ],
      "difficulty":"advanced",
      "technicalComplexity":3,
      "stabilityDemand":3,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "supported_hanging"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "single-arm-cable-extension":{
      "aliases":[
        "Tríceps unilateral en polea"
      ],
      "movementPattern":"elbow_extension",
      "movementSubpattern":"single_arm_cable_pushdown",
      "primaryMuscles":[
        "triceps"
      ],
      "secondaryMuscles":[],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "db-overhead-triceps-extension":{
      "aliases":[
        "Copa de tríceps",
        "Extensión overhead con mancuerna"
      ],
      "movementPattern":"elbow_extension",
      "movementSubpattern":"dumbbell_overhead_triceps_extension",
      "primaryMuscles":[
        "triceps"
      ],
      "secondaryMuscles":[
        "trunk"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "calf-raise":{
      "aliases":[
        "Gemelo máquina"
      ],
      "movementPattern":"calf_raise",
      "movementSubpattern":"machine_calf_raise",
      "primaryMuscles":[
        "calves"
      ],
      "secondaryMuscles":[],
      "requiredEquipment":[
        "calf_raise_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "standing-calf-raise":{
      "aliases":[
        "Gemelos de pie"
      ],
      "movementPattern":"calf_raise",
      "movementSubpattern":"standing_calf_raise",
      "primaryMuscles":[
        "calves"
      ],
      "secondaryMuscles":[],
      "requiredEquipment":[
        "dumbbells",
        "step"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":3,
      "balanceDemand":3,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "seated-calf-raise":{
      "aliases":[
        "Gemelo sentado",
        "Sóleo sentado"
      ],
      "movementPattern":"calf_raise",
      "movementSubpattern":"seated_calf_raise",
      "primaryMuscles":[
        "calves"
      ],
      "secondaryMuscles":[],
      "requiredEquipment":[
        "seated_calf_raise_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "leg-press-calf-raise":{
      "aliases":[
        "Gemelos en prensa"
      ],
      "movementPattern":"calf_raise",
      "movementSubpattern":"leg_press_calf_raise",
      "primaryMuscles":[
        "calves"
      ],
      "secondaryMuscles":[],
      "requiredEquipment":[
        "leg_press"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "machine_stack"
      ]
    },
    "plank":{
      "aliases":[
        "Plancha frontal"
      ],
      "movementPattern":"anti_extension_core",
      "movementSubpattern":"forearm_plank",
      "primaryMuscles":[
        "trunk"
      ],
      "secondaryMuscles":[
        "shoulders",
        "glutes"
      ],
      "requiredEquipment":[
        "bodyweight",
        "mat"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "prone"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "side-plank":{
      "aliases":[
        "Plancha de lado"
      ],
      "movementPattern":"lateral_core",
      "movementSubpattern":"side_plank",
      "primaryMuscles":[
        "obliques",
        "trunk"
      ],
      "secondaryMuscles":[
        "gluteus_medius",
        "shoulders"
      ],
      "requiredEquipment":[
        "bodyweight",
        "mat"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":3,
      "balanceDemand":2,
      "supported":false,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "side_lying"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "dead-bug":{
      "aliases":[
        "Bicho muerto"
      ],
      "movementPattern":"anti_extension_core",
      "movementSubpattern":"dead_bug",
      "primaryMuscles":[
        "trunk"
      ],
      "secondaryMuscles":[
        "hip_flexors"
      ],
      "requiredEquipment":[
        "bodyweight",
        "mat"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "supine"
      ],
      "loadingTypes":[
        "bodyweight"
      ],
      "prolongedSupine":true
    },
    "bird-dog":{
      "aliases":[
        "Perro de caza",
        "Extensión contralateral en cuadrupedia"
      ],
      "movementPattern":"anti_rotation_core",
      "movementSubpattern":"quadruped_bird_dog",
      "primaryMuscles":[
        "trunk"
      ],
      "secondaryMuscles":[
        "glutes",
        "shoulders",
        "spinal_erectors"
      ],
      "requiredEquipment":[
        "bodyweight",
        "mat"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":3,
      "balanceDemand":2,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "quadruped"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "pallof-press":{
      "aliases":[
        "Pallof press",
        "Antirrotación en polea"
      ],
      "movementPattern":"anti_rotation_core",
      "movementSubpattern":"standing_pallof_press",
      "primaryMuscles":[
        "trunk",
        "obliques"
      ],
      "secondaryMuscles":[
        "shoulders"
      ],
      "requiredEquipment":[
        "cable_machine"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":3,
      "balanceDemand":2,
      "supported":false,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "cable-crunch":{
      "aliases":[
        "Encogimiento en polea"
      ],
      "movementPattern":"trunk_flexion",
      "movementSubpattern":"kneeling_cable_crunch",
      "primaryMuscles":[
        "rectus_abdominis"
      ],
      "secondaryMuscles":[
        "obliques"
      ],
      "requiredEquipment":[
        "cable_machine",
        "mat"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "kneeling"
      ],
      "loadingTypes":[
        "cable"
      ]
    },
    "reverse-crunch":{
      "aliases":[
        "Encogimiento inverso"
      ],
      "movementPattern":"trunk_flexion",
      "movementSubpattern":"reverse_crunch",
      "primaryMuscles":[
        "rectus_abdominis"
      ],
      "secondaryMuscles":[
        "obliques",
        "hip_flexors"
      ],
      "requiredEquipment":[
        "bodyweight",
        "mat"
      ],
      "difficulty":"beginner",
      "technicalComplexity":2,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "supine"
      ],
      "loadingTypes":[
        "bodyweight"
      ],
      "prolongedSupine":true
    },
    "hanging-knee-raise":{
      "aliases":[
        "Rodillas al pecho colgado"
      ],
      "movementPattern":"hip_flexion_core",
      "movementSubpattern":"hanging_knee_raise",
      "primaryMuscles":[
        "rectus_abdominis",
        "hip_flexors"
      ],
      "secondaryMuscles":[
        "forearms",
        "latissimus_dorsi"
      ],
      "requiredEquipment":[
        "pull_up_bar"
      ],
      "difficulty":"intermediate",
      "technicalComplexity":3,
      "stabilityDemand":4,
      "balanceDemand":2,
      "supported":false,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "hanging"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "ab-wheel-rollout":{
      "aliases":[
        "Ab wheel",
        "Rollout abdominal"
      ],
      "movementPattern":"anti_extension_core",
      "movementSubpattern":"kneeling_ab_wheel_rollout",
      "primaryMuscles":[
        "trunk"
      ],
      "secondaryMuscles":[
        "latissimus_dorsi",
        "shoulders"
      ],
      "requiredEquipment":[
        "ab_wheel",
        "mat"
      ],
      "difficulty":"advanced",
      "technicalComplexity":3,
      "stabilityDemand":4,
      "balanceDemand":2,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "kneeling"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "farmer-carry":{
      "aliases":[
        "Farmer walk",
        "Caminata del granjero"
      ],
      "movementPattern":"loaded_carry",
      "movementSubpattern":"bilateral_farmer_carry",
      "primaryMuscles":[
        "forearms",
        "upper_traps",
        "trunk"
      ],
      "secondaryMuscles":[
        "glutes",
        "calves",
        "shoulders"
      ],
      "requiredEquipment":[
        "dumbbells"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":3,
      "balanceDemand":3,
      "supported":false,
      "closedChain":true,
      "unilateral":false,
      "bodyPositions":[
        "walking"
      ],
      "loadingTypes":[
        "free_weight"
      ]
    },
    "treadmill-walk":{
      "aliases":[
        "Andar en cinta",
        "Cinta caminando"
      ],
      "movementPattern":"locomotion",
      "movementSubpattern":"treadmill_walking",
      "primaryMuscles":[
        "cardiorespiratory"
      ],
      "secondaryMuscles":[
        "quadriceps",
        "glutes",
        "calves"
      ],
      "requiredEquipment":[
        "treadmill"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":2,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "walking"
      ],
      "loadingTypes":[
        "cardio_machine"
      ]
    },
    "stationary-bike":{
      "aliases":[
        "Bici estática",
        "Bicicleta indoor"
      ],
      "movementPattern":"locomotion",
      "movementSubpattern":"stationary_cycling",
      "primaryMuscles":[
        "cardiorespiratory"
      ],
      "secondaryMuscles":[
        "quadriceps",
        "glutes",
        "calves"
      ],
      "requiredEquipment":[
        "stationary_bike"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "seated"
      ],
      "loadingTypes":[
        "cardio_machine"
      ]
    },
    "elliptical":{
      "aliases":[
        "Máquina elíptica"
      ],
      "movementPattern":"locomotion",
      "movementSubpattern":"elliptical_training",
      "primaryMuscles":[
        "cardiorespiratory"
      ],
      "secondaryMuscles":[
        "quadriceps",
        "glutes",
        "calves"
      ],
      "requiredEquipment":[
        "elliptical"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "standing"
      ],
      "loadingTypes":[
        "cardio_machine"
      ]
    },
    "cat-cow":{
      "aliases":[
        "Cat cow",
        "Gato vaca"
      ],
      "movementPattern":"spinal_mobility",
      "movementSubpattern":"quadruped_cat_cow",
      "primaryMuscles":[
        "spinal_mobility"
      ],
      "secondaryMuscles":[
        "trunk"
      ],
      "requiredEquipment":[
        "bodyweight",
        "mat"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":1,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":false,
      "bodyPositions":[
        "quadruped"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "thoracic-rotation":{
      "aliases":[
        "Rotación torácica",
        "Open book cuadrupedia"
      ],
      "movementPattern":"thoracic_rotation",
      "movementSubpattern":"quadruped_thoracic_rotation",
      "primaryMuscles":[
        "thoracic_spine"
      ],
      "secondaryMuscles":[
        "shoulders",
        "trunk"
      ],
      "requiredEquipment":[
        "bodyweight",
        "mat"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "quadruped"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    },
    "hip-flexor-stretch":{
      "aliases":[
        "Estiramiento psoas",
        "Estiramiento flexor de cadera"
      ],
      "movementPattern":"hip_flexor_mobility",
      "movementSubpattern":"half_kneeling_hip_flexor_stretch",
      "primaryMuscles":[
        "hip_flexors"
      ],
      "secondaryMuscles":[
        "quadriceps"
      ],
      "requiredEquipment":[
        "bodyweight",
        "mat"
      ],
      "difficulty":"beginner",
      "technicalComplexity":1,
      "stabilityDemand":2,
      "balanceDemand":1,
      "supported":true,
      "closedChain":false,
      "unilateral":true,
      "bodyPositions":[
        "half_kneeling"
      ],
      "loadingTypes":[
        "bodyweight"
      ]
    }
  });

  function clone(value){return value===undefined?undefined:JSON.parse(JSON.stringify(value));}
  function cleanText(value,max=500){return String(value??"").trim().replace(/\s+/g," ").slice(0,max);}
  function normalizeToken(value){
    return cleanText(value,120).normalize("NFD").replace(/[\u0300-\u036f]/g,"")
      .toLowerCase().replace(/[‐‑‒–—/]+/g," ").replace(/[^a-z0-9]+/g," ").trim();
  }
  function slug(value){
    return normalizeToken(value).replace(/\s+/g,"_")||"custom_exercise";
  }
  function exerciseIdentityKey(input={}){
    const explicit=cleanText(input.legacyIdentityKey,300);
    if(explicit) return explicit;
    const inheritedId=cleanText(input.legacyDuplicateId||input.id,120)||`custom-${slug(input.name)}`;
    return `${slug(inheritedId)}::${slug(input.name)}`;
  }
  function uniqueStrings(value,max=50){
    const list=Array.isArray(value)?value:[value];
    return [...new Set(list.map(item=>cleanText(item,120)).filter(Boolean))].slice(0,max);
  }
  function boundedNumber(value,fallback,min,max){
    const parsed=Number(value);
    return Number.isFinite(parsed)?Math.max(min,Math.min(max,parsed)):fallback;
  }
  function legacyMuscleIds(value){
    const normalized=normalizeToken(value);
    const mappings={
      pecho:["chest"],espalda:["upper_back","latissimus_dorsi"],piernas:["quadriceps","glutes"],
      isquios:["hamstrings"],hombros:["deltoids"],biceps:["biceps"],triceps:["triceps"],
      gemelos:["calves"],core:["trunk"]
    };
    return mappings[normalized]||[];
  }
  function legacyEquipmentIds(value,id=""){
    const metadata=LEGACY_EXERCISE_METADATA[id];
    if(metadata?.requiredEquipment) return [...metadata.requiredEquipment];
    const mapped=EQUIPMENT_ALIASES[normalizeToken(value)];
    if(!mapped||mapped==="machine") return [];
    return EQUIPMENT_PRESETS[mapped]?[...EQUIPMENT_PRESETS[mapped]]:[mapped];
  }
  function normalizeEquipmentSelection(value){
    const source=Array.isArray(value)?value:[value];
    const equipment=[];
    source.filter(item=>item!==null&&item!==undefined&&String(item).trim()).forEach(item=>{
      const token=normalizeToken(item);
      const mapped=EQUIPMENT_ALIASES[token]||token.replace(/\s+/g,"_");
      const values=EQUIPMENT_PRESETS[mapped]||[mapped];
      values.filter(Boolean).forEach(id=>{if(!equipment.includes(id)) equipment.push(id);});
    });
    return equipment;
  }
  function trainingLocationsForEquipment(equipmentIds){
    if(!equipmentIds.length) return [];
    const gymOnly=new Set([
      "smith_machine","cable_machine","chest_press_machine","shoulder_press_machine",
      "lateral_raise_machine","leg_press","leg_extension","seated_leg_curl",
      "lying_leg_curl","hip_thrust_machine","hip_abduction_machine",
      "hip_adduction_machine","lat_pulldown","seated_row","row_machine",
      "t_bar_row_machine","pec_deck","hack_squat_machine","calf_raise_machine",
      "seated_calf_raise_machine","assisted_pullup_dip_machine","nordic_bench",
      "treadmill","stationary_bike","elliptical"
    ]);
    return equipmentIds.some(id=>gymOnly.has(id))?["gym"]:["gym","home"];
  }
  function legacyCategory(item){
    const type=normalizeToken(item.type);
    if(type==="cardio") return "cardio";
    if(type==="movilidad") return "mobility";
    return "strength";
  }
  function defaultRecordType(item,metadata){
    if(item.recordTypes?.length) return item.recordTypes[0];
    if(metadata?.movementPattern==="anti_extension_core"||normalizeToken(item.type)==="tiempo") return "duration";
    if(metadata?.loadingTypes?.includes("bodyweight")) return "bodyweight_reps";
    return "weight_reps";
  }
  function normalizePregnancyMetadata(input={},metadata={}){
    const source=input&&typeof input==="object"?input:{};
    return {
      eligibleForConsideration:Boolean(source.eligibleForConsideration),
      requiresProfessionalClearance:source.requiresProfessionalClearance!==false,
      prohibitedByProduct:Boolean(source.prohibitedByProduct),
      stageTags:uniqueStrings(source.stageTags||[]),
      positionFlags:uniqueStrings(source.positionFlags||metadata.bodyPositions||[]),
      balanceRisk:["low","moderate","high","unknown"].includes(source.balanceRisk)?source.balanceRisk:"unknown",
      fallRisk:["low","moderate","high","unknown"].includes(source.fallRisk)?source.fallRisk:"unknown",
      impactLevel:["low","moderate","high","unknown"].includes(source.impactLevel)?source.impactLevel:"unknown",
      prolongedSupine:Boolean(source.prolongedSupine??metadata.prolongedSupine),
      abdominalPressureDemand:["low","moderate","high","unknown"].includes(source.abdominalPressureDemand)
        ?source.abdominalPressureDemand:"unknown",
      notes:uniqueStrings(source.notes?.length?source.notes:["Pendiente de revisión específica antes de utilizarse durante el embarazo."])
    };
  }
  function normalizePrescription(input={},recordType="weight_reps"){
    const repRange=input.repRange&&typeof input.repRange==="object"
      ?{min:boundedNumber(input.repRange.min,8,1,100),max:boundedNumber(input.repRange.max,12,1,100)}
      :recordType==="duration"?null:{min:8,max:12};
    if(repRange&&repRange.max<repRange.min) repRange.max=repRange.min;
    const targetRir=input.targetRir&&typeof input.targetRir==="object"
      ?{min:boundedNumber(input.targetRir.min,2,0,10),max:boundedNumber(input.targetRir.max,3,0,10)}
      :{min:2,max:3};
    if(targetRir.max<targetRir.min) targetRir.max=targetRir.min;
    return {
      sets:boundedNumber(input.sets,3,1,10),
      repRange,
      targetRir,
      restSeconds:boundedNumber(input.restSeconds,90,15,600),
      incrementKg:boundedNumber(input.incrementKg,recordType==="weight_reps"?2.5:0,0,100)
    };
  }
  function normalizeExerciseDefinition(input={},options={}){
    const timestamp=options.timestamp||new Date(0).toISOString();
    const originalId=cleanText(input.id,120);
    const id=originalId||`custom-${slug(input.name)}`;
    const metadata=LEGACY_EXERCISE_METADATA[id]||{};
    const requiredEquipment=uniqueStrings(
      input.requiredEquipment||input.equipmentIds||legacyEquipmentIds(input.equipment,id)
    );
    const primaryMuscles=uniqueStrings(input.primaryMuscles?.length?input.primaryMuscles:metadata.primaryMuscles||legacyMuscleIds(input.muscle));
    const recordType=defaultRecordType(input,metadata);
    const recordTypes=uniqueStrings(input.recordTypes?.length?input.recordTypes:[recordType]);
    const movementPattern=MOVEMENT_PATTERNS.includes(input.movementPattern)
      ?input.movementPattern
      :metadata.movementPattern||null;
    const category=EXERCISE_CATEGORIES.includes(input.category)?input.category:legacyCategory(input);
    const isReviewed=Boolean(movementPattern&&primaryMuscles.length&&requiredEquipment.length);
    const fallbackTimestamp=LEGACY_EXERCISE_METADATA[id]&&!input.custom
      ?new Date(0).toISOString()
      :timestamp;
    const createdAt=input.createdAt||fallbackTimestamp;
    const updatedAt=options.touchUpdatedAt?timestamp:(input.updatedAt||fallbackTimestamp);
    const legacyEquipment=cleanText(input.equipment,80)||(
      requiredEquipment.includes("bodyweight")?"Peso corporal":
      requiredEquipment.includes("dumbbells")?"Mancuernas":
      requiredEquipment.includes("barbell")?"Barra":
      requiredEquipment.includes("cable_machine")?"Polea":
      requiredEquipment.some(item=>item.includes("machine")||item==="leg_press"||item==="pec_deck"||item==="lat_pulldown"||item==="seated_row")?"Máquina":
      requiredEquipment.includes("ez_bar")?"Barra EZ":
      requiredEquipment.includes("trap_bar")?"Barra hexagonal":""
    );
    return {
      ...clone(input),
      id,
      schemaVersion:EXERCISE_SCHEMA_VERSION,
      legacyIdentityKey:exerciseIdentityKey({...input,id}),
      name:cleanText(input.name,160)||"Ejercicio sin nombre",
      aliases:uniqueStrings(input.aliases?.length?input.aliases:metadata.aliases||[]),
      category,
      movementPattern,
      movementSubpattern:cleanText(input.movementSubpattern||metadata.movementSubpattern,120)||null,
      primaryMuscles,
      secondaryMuscles:uniqueStrings(input.secondaryMuscles?.length?input.secondaryMuscles:metadata.secondaryMuscles||[]),
      requiredEquipment,
      trainingLocations:uniqueStrings(input.trainingLocations?.length?input.trainingLocations:trainingLocationsForEquipment(requiredEquipment)),
      difficulty:EXPERIENCE_LEVELS.includes(input.difficulty)?input.difficulty:(metadata.difficulty||"beginner"),
      technicalComplexity:boundedNumber(input.technicalComplexity,metadata.technicalComplexity||1,1,5),
      stabilityDemand:boundedNumber(input.stabilityDemand,metadata.stabilityDemand||1,1,5),
      balanceDemand:boundedNumber(input.balanceDemand,metadata.balanceDemand||1,1,5),
      unilateral:Boolean(input.unilateral??metadata.unilateral),
      supported:Boolean(input.supported??metadata.supported),
      closedChain:Boolean(input.closedChain??metadata.closedChain),
      bodyPositions:uniqueStrings(input.bodyPositions?.length?input.bodyPositions:metadata.bodyPositions||[]),
      loadingTypes:uniqueStrings(input.loadingTypes?.length?input.loadingTypes:metadata.loadingTypes||[]),
      recordTypes,
      suitableGoals:uniqueStrings(input.suitableGoals?.length?input.suitableGoals:[
        "return_to_training","muscle_gain","general_health","maintenance"
      ]),
      lessSuitableGoals:uniqueStrings(input.lessSuitableGoals||[]),
      experienceLevels:uniqueStrings(input.experienceLevels?.length?input.experienceLevels:EXPERIENCE_LEVELS),
      defaultPrescription:normalizePrescription(input.defaultPrescription,recordTypes[0]),
      cautionFlags:uniqueStrings(input.cautionFlags||[]),
      exclusionFlags:uniqueStrings(input.exclusionFlags||[]),
      substitutionGroups:uniqueStrings(input.substitutionGroups?.length?input.substitutionGroups:[
        movementPattern,...primaryMuscles
      ].filter(Boolean)),
      alternatives:uniqueStrings(input.alternatives||[]),
      pregnancy:normalizePregnancyMetadata(input.pregnancy,metadata),
      instructions:{
        short:cleanText(input.instructions?.short??input.notes,500),
        breathing:cleanText(input.instructions?.breathing,300),
        setup:uniqueStrings(input.instructions?.setup||[]),
        execution:uniqueStrings(input.instructions?.execution||[]),
        stopIf:uniqueStrings(input.instructions?.stopIf||[])
      },
      source:input.source||((input.custom||!LEGACY_EXERCISE_METADATA[id])?"custom":"built_in"),
      migrationStatus:isReviewed?"ready":"needs_review",
      muscle:cleanText(input.muscle,80),
      equipment:legacyEquipment,
      type:cleanText(input.type,80),
      favorite:Boolean(input.favorite),
      custom:Boolean(input.custom||!LEGACY_EXERCISE_METADATA[id]),
      notes:cleanText(input.notes,1000),
      createdAt,
      updatedAt
    };
  }
  function migrateExerciseLibrary(items,options={}){
    const source=Array.isArray(items)?items:[];
    const timestamp=options.timestamp||new Date().toISOString();
    const usedIds=new Set();
    const library=source.map(item=>{
      const normalized=normalizeExerciseDefinition(item,{
        timestamp,
        touchUpdatedAt:Boolean(options.touchUpdatedAt)
      });
      const base=normalized.id;
      let id=base;
      let suffix=2;
      while(usedIds.has(id)) id=`${base}-${suffix++}`;
      usedIds.add(id);
      return id===base?normalized:{...normalized,id,legacyDuplicateId:base,migrationStatus:"needs_review"};
    });
    return {
      domainVersion:DOMAIN_VERSION,
      exerciseSchemaVersion:EXERCISE_SCHEMA_VERSION,
      library,
      changed:JSON.stringify(source)!==JSON.stringify(library),
      validation:library.map(exercise=>({id:exercise.id,...validateExerciseDefinition(exercise)}))
    };
  }
  function mergeExerciseLibraries(currentItems,incomingItems,options={}){
    const timestamp=options.timestamp||new Date().toISOString();
    const currentSource=Array.isArray(currentItems)?currentItems:[];
    const incomingSource=Array.isArray(incomingItems)?incomingItems:[];
    const merged=migrateExerciseLibrary(currentSource,{timestamp}).library.map(item=>clone(item));
    const identityIndexes=new Map();
    merged.forEach((item,index)=>identityIndexes.set(exerciseIdentityKey(item),index));
    const normalizedIncoming=migrateExerciseLibrary(incomingSource,{timestamp}).library;

    normalizedIncoming.forEach((incoming,index)=>{
      const identity=exerciseIdentityKey(incoming);
      const existingIndex=identityIndexes.get(identity);
      if(existingIndex===undefined){
        identityIndexes.set(identity,merged.length);
        merged.push(incoming);
        return;
      }

      const existing=merged[existingIndex];
      const rawIncoming=incomingSource[index]||{};
      const currentTime=Date.parse(existing.updatedAt||"");
      const incomingTime=Date.parse(rawIncoming.updatedAt||"");
      const incomingIsNewer=Number.isFinite(incomingTime)&&(
        !Number.isFinite(currentTime)||incomingTime>currentTime
      );
      if(!incomingIsNewer) return;
      merged[existingIndex]={
        ...incoming,
        id:existing.id,
        legacyDuplicateId:existing.legacyDuplicateId||incoming.legacyDuplicateId,
        legacyIdentityKey:identity,
        createdAt:existing.createdAt||incoming.createdAt,
        updatedAt:rawIncoming.updatedAt
      };
    });

    const result=migrateExerciseLibrary(merged,{timestamp});
    return {
      ...result,
      mergePolicy:"same_origin_id_and_normalized_name",
      currentCount:currentSource.length,
      incomingCount:incomingSource.length
    };
  }
  function validateExerciseDefinition(exercise={}){
    const errors=[],warnings=[];
    if(!cleanText(exercise.id)) errors.push("exercise_id_required");
    if(!cleanText(exercise.name)) errors.push("exercise_name_required");
    if(!EXERCISE_CATEGORIES.includes(exercise.category)) errors.push("invalid_category");
    if(exercise.movementPattern===null||exercise.movementPattern===undefined) warnings.push("movement_pattern_review_required");
    else if(!MOVEMENT_PATTERNS.includes(exercise.movementPattern)) errors.push("invalid_movement_pattern");
    if(!Array.isArray(exercise.primaryMuscles)||!exercise.primaryMuscles.length) warnings.push("primary_muscles_review_required");
    if(!Array.isArray(exercise.requiredEquipment)||!exercise.requiredEquipment.length) warnings.push("equipment_review_required");
    if(!Array.isArray(exercise.recordTypes)||exercise.recordTypes.some(type=>!RECORD_TYPES.includes(type))){
      errors.push("invalid_record_type");
    }
    if(exercise.pregnancy?.eligibleForConsideration&&exercise.pregnancy?.stageTags?.length===0){
      warnings.push("pregnancy_review_required");
    }
    return {valid:errors.length===0,errors,warnings};
  }
  function getProgrammingRule(goalId){
    return clone(PROGRAMMING_RULES[goalId]||PROGRAMMING_RULES.general_health);
  }
  function buildExerciseDomainMigration(input={}){
    const timestamp=input.timestamp||new Date().toISOString();
    const migrated=migrateExerciseLibrary(input.exerciseLibrary,{timestamp});
    const originalProfile=input.userProfile&&typeof input.userProfile==="object"
      ?clone(input.userProfile)
      :null;
    const normalizedEquipment=originalProfile
      ?normalizeEquipmentSelection(originalProfile.availableEquipment)
      :[];
    const userProfile=originalProfile
      ?{
        ...originalProfile,
        availableEquipment:normalizedEquipment,
        updatedAt:normalizedEquipment.join("\u0000")===
          uniqueStrings(originalProfile.availableEquipment||[]).join("\u0000")
          ?originalProfile.updatedAt
          :timestamp
      }
      :null;
    return {
      domainVersion:DOMAIN_VERSION,
      exerciseSchemaVersion:EXERCISE_SCHEMA_VERSION,
      exerciseLibrary:migrated.library,
      userProfile,
      validation:migrated.validation
    };
  }

  global.GymOSExerciseDomain=Object.freeze({
    DOMAIN_VERSION,EXERCISE_SCHEMA_VERSION,
    MOVEMENT_PATTERNS,EXERCISE_CATEGORIES,EQUIPMENT_TAXONOMY,EQUIPMENT_PRESETS,
    EXPERIENCE_LEVELS,RECORD_TYPES,PROGRAMMING_PRIORITY,PROGRAMMING_RULES,
    LEGACY_EXERCISE_METADATA,
    normalizeToken,normalizeEquipmentSelection,exerciseIdentityKey,normalizeExerciseDefinition,
    migrateExerciseLibrary,mergeExerciseLibraries,validateExerciseDefinition,getProgrammingRule,
    buildExerciseDomainMigration
  });
})(typeof window!=="undefined"?window:globalThis);
